/**
 * AI_DESK — Interactive Onboarding Wizard
 *
 * Guides a fresh install through every required setup step:
 *   1. Welcome + existing setup check
 *   2. Master encryption key (auto-generate or bring your own)
 *   3. API credentials — Anthropic and/or Google
 *   4. Gateway config (port, bind, sandbox mode)
 *   5. Write .env + ai-desk.json
 *   6. Generate initial auth token
 *   7. Quick security audit
 *   8. Next steps
 *
 * Uses only Node built-ins — no extra dependencies.
 */
import { createInterface } from 'node:readline';
import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = dirname(__filename);

// ─── ANSI helpers ────────────────────────────────────────────────────────────

const c = {
  reset:  '\x1b[0m',
  bold:   '\x1b[1m',
  dim:    '\x1b[2m',
  green:  '\x1b[32m',
  yellow: '\x1b[33m',
  blue:   '\x1b[34m',
  cyan:   '\x1b[36m',
  red:    '\x1b[31m',
  white:  '\x1b[97m',
  bg:     '\x1b[40m',
};
const green  = (s: string) => `${c.green}${s}${c.reset}`;
const yellow = (s: string) => `${c.yellow}${s}${c.reset}`;
const blue   = (s: string) => `${c.blue}${s}${c.reset}`;
const cyan   = (s: string) => `${c.cyan}${s}${c.reset}`;
const red    = (s: string) => `${c.red}${s}${c.reset}`;
const bold   = (s: string) => `${c.bold}${s}${c.reset}`;
const dim    = (s: string) => `${c.dim}${s}${c.reset}`;

const DIVIDER = dim('─'.repeat(60));

// ─── Prompt helpers ──────────────────────────────────────────────────────────

function createRl() {
  return createInterface({ input: process.stdin, output: process.stdout, terminal: true });
}

function ask(question: string, defaultValue = ''): Promise<string> {
  return new Promise(resolve => {
    const rl = createRl();
    const prompt = defaultValue
      ? `${question} ${dim(`[${defaultValue}]`)} › `
      : `${question} › `;
    rl.question(prompt, answer => {
      rl.close();
      resolve(answer.trim() || defaultValue);
    });
  });
}

async function askSecret(question: string): Promise<string> {
  // If not a TTY (piped), fall back to plain ask
  if (!process.stdin.isTTY) return ask(question);

  return new Promise(resolve => {
    process.stdout.write(`${question} › `);

    const chunks: string[] = [];
    let muted = false;

    process.stdin.setRawMode(true);
    process.stdin.resume();
    process.stdin.setEncoding('utf-8');

    muted = true;
    const onData = (char: string) => {
      switch (char) {
        case '\r':
        case '\n':
          process.stdin.setRawMode(false);
          process.stdin.pause();
          process.stdin.removeListener('data', onData);
          process.stdout.write('\n');
          resolve(chunks.join(''));
          break;
        case '\x03': // Ctrl+C
          process.stdout.write('\n');
          process.exit(0);
          break;
        case '\x7f': // Backspace
          if (chunks.length > 0) {
            chunks.pop();
            if (muted) process.stdout.write('\b \b');
          }
          break;
        default:
          chunks.push(char);
          if (muted) process.stdout.write('*');
      }
    };

    process.stdin.on('data', onData);
  });
}

async function confirm(question: string, defaultYes = true): Promise<boolean> {
  const hint = defaultYes ? 'Y/n' : 'y/N';
  const answer = await ask(`${question} ${dim(`(${hint})`)}`);
  if (!answer) return defaultYes;
  return answer.toLowerCase().startsWith('y');
}

function print(msg = '') { process.stdout.write(msg + '\n'); }
function step(n: number, total: number, title: string) {
  print(`\n${bold(cyan(`Step ${n}/${total}`))}  ${bold(title)}`);
  print(DIVIDER);
}
function ok(msg: string)   { print(`  ${green('✔')} ${msg}`); }
function warn(msg: string) { print(`  ${yellow('⚠')} ${msg}`); }
function info(msg: string) { print(`  ${blue('ℹ')} ${msg}`); }
function err(msg: string)  { print(`  ${red('✖')} ${msg}`); }

// ─── File helpers ─────────────────────────────────────────────────────────────

function fileExists(p: string): boolean { return existsSync(resolve(p)); }

function parseEnvFile(path: string): Record<string, string> {
  if (!fileExists(path)) return {};
  const result: Record<string, string> = {};
  for (const line of readFileSync(resolve(path), 'utf-8').split('\n')) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (m) result[m[1]] = m[2].replace(/^"(.*)"$/, '$1').replace(/^'(.*)'$/, '$1');
  }
  return result;
}

function buildEnvFile(vars: Record<string, string>): string {
  const lines = [
    '# AI_DESK — Environment Variables',
    '# Generated by: ai-desk onboard',
    '# Keep this file private — never commit to version control.',
    '',
    '# ── Gateway ─────────────────────────────────────────────',
    `AI_DESK_MASTER_KEY=${vars['AI_DESK_MASTER_KEY'] ?? ''}`,
    '',
    '# ── Model Providers ─────────────────────────────────────',
    `ANTHROPIC_API_KEY=${vars['ANTHROPIC_API_KEY'] ?? ''}`,
    `GOOGLE_AI_API_KEY=${vars['GOOGLE_AI_API_KEY'] ?? ''}`,
    '',
    '# ── Google OAuth (optional) ──────────────────────────────',
    `# GOOGLE_CLIENT_ID=${vars['GOOGLE_CLIENT_ID'] ?? ''}`,
    `# GOOGLE_CLIENT_SECRET=${vars['GOOGLE_CLIENT_SECRET'] ?? ''}`,
    '',
    '# ── Messaging (optional) ─────────────────────────────────',
    `# TELEGRAM_BOT_TOKEN=${vars['TELEGRAM_BOT_TOKEN'] ?? ''}`,
    `# DISCORD_BOT_TOKEN=${vars['DISCORD_BOT_TOKEN'] ?? ''}`,
  ];
  return lines.join('\n') + '\n';
}

function minimalConfig(port: number, bind: string, sandbox: string): string {
  return JSON.stringify({
    gateway: {
      bind,
      port,
      auth: { mode: 'token', maxFailedAttempts: 5, lockoutDurationMs: 300000, tokenExpiryMs: 86400000 },
      rateLimit: { maxPerSecond: 10, maxConnections: 50 },
      maxFrameSize: 1048576,
      heartbeatIntervalMs: 30000,
    },
    agents: {
      defaults: {
        model: {
          primary: 'anthropic/claude-sonnet-4-6',
          failover: ['google/gemini-2.5-flash'],
          compaction: 'anthropic/claude-haiku-4-5-20251001',
        },
        timeoutSeconds: 172800,
        sandbox: {
          mode: sandbox,
          timeoutMs: 30000,
          maxMemoryMb: 512,
          networkAccess: false,
        },
        tools: { profile: 'deny-all' },
        budget: {
          daily:   { tokens: 500000,   cost: 5.0 },
          monthly: { tokens: 10000000, cost: 50.0 },
          perRun:  { maxTokens: 50000 },
          warningThreshold: 0.8,
          action: 'warn',
        },
        subagents: {
          model: 'google/gemini-2.5-flash',
          maxDepth: 3,
          maxConcurrent: 5,
          sandbox: 'require',
          runTimeoutSeconds: 300,
          budget: 'inherit',
        },
      },
      list: [
        { id: 'main', default: true, workspace: '.', tools: { profile: 'readonly' } },
      ],
    },
    cache:  { enabled: true, backend: 'sqlite', ttlSeconds: 3600 },
    memory: { backend: 'none', compaction: { threshold: 0.6, model: 'anthropic/claude-haiku-4-5-20251001' } },
    mcp:    { security: { sandboxAll: true, denyCapabilities: [], perServerBudget: { dailyTokens: 50000 } }, servers: {} },
    notifications: { budgetAlerts: true, subagentCompletion: true, securityAlerts: true },
  }, null, 2);
}

// ─── Main ─────────────────────────────────────────────────────────────────────

export async function runOnboard(opts: { installDaemon?: boolean } = {}): Promise<void> {
  const TOTAL_STEPS = 8;
  let daemonInstalled = false;

  // ── Banner ───────────────────────────────────────────────────────────────
  print();
  print(`${c.bold}${c.cyan}╔════════════════════════════════════════════════════════════╗${c.reset}`);
  print(`${c.bold}${c.cyan}║${c.reset}  ${c.bold}${c.white}AI_DESK${c.reset}  ${c.dim}Interactive Setup Wizard${c.reset}${' '.repeat(30)}${c.bold}${c.cyan}║${c.reset}`);
  print(`${c.bold}${c.cyan}╚════════════════════════════════════════════════════════════╝${c.reset}`);
  print();
  print('  This wizard will walk you through a complete gateway setup.');
  print(`  ${dim('Press Ctrl+C at any time to cancel without saving.')}`);
  print();

  // ── Existing setup check ─────────────────────────────────────────────────
  const envExists    = fileExists('.env');
  const configExists = fileExists('ai-desk.json');
  const existingEnv  = parseEnvFile('.env');

  if (envExists || configExists) {
    warn('Existing files detected:');
    if (envExists)    info(`.env found — existing values will be preserved`);
    if (configExists) info(`ai-desk.json found — will not be overwritten`);
    print();
    const proceed = await confirm('Continue? (existing .env values are kept, new ones merged)');
    if (!proceed) { print('\nCancelled.\n'); return; }
  }

  const collected: Record<string, string> = { ...existingEnv };

  // ─────────────────────────────────────────────────────────────────────────
  step(1, TOTAL_STEPS, 'Master Encryption Key');
  print('  Encrypts all secrets, sessions, tokens, and audit log at rest.');
  print(`  ${red('If lost, all stored data is unrecoverable.')} Store it safely.\n`);

  if (collected['AI_DESK_MASTER_KEY']) {
    ok('AI_DESK_MASTER_KEY already set — keeping existing value.');
  } else {
    const autoGen = await confirm('Auto-generate a secure key?');
    if (autoGen) {
      collected['AI_DESK_MASTER_KEY'] = randomBytes(32).toString('hex');
      ok(`Generated: ${bold(collected['AI_DESK_MASTER_KEY'])}`);
      warn('Copy this key somewhere safe before continuing.');
      await ask('\n  Press Enter to continue');
    } else {
      const key = await askSecret('Enter your master key (min 16 chars)');
      if (key.length < 16) {
        err('Key too short (min 16 chars). Aborting.');
        process.exit(1);
      }
      collected['AI_DESK_MASTER_KEY'] = key;
      ok('Master key set.');
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  step(2, TOTAL_STEPS, 'Anthropic API Key');
  print(`  Required to use Claude models. Get one at ${cyan('console.anthropic.com')}\n`);

  if (collected['ANTHROPIC_API_KEY']) {
    ok(`ANTHROPIC_API_KEY already set — keeping. ${dim('(Leave blank below to keep, or enter new key)')}`);
    const replace = await askSecret('New key (blank = keep existing)');
    if (replace) collected['ANTHROPIC_API_KEY'] = replace;
  } else {
    const key = await askSecret('Anthropic API key (blank = skip)');
    if (key) {
      collected['ANTHROPIC_API_KEY'] = key;
      ok('Anthropic key set.');
    } else {
      warn('Skipped. You can add it later via Dashboard → Credentials or .env');
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  step(3, TOTAL_STEPS, 'Google / Gemini API Key');
  print(`  Optional failover provider. Get one at ${cyan('aistudio.google.com')}\n`);

  if (collected['GOOGLE_AI_API_KEY']) {
    ok(`GOOGLE_AI_API_KEY already set — keeping.`);
    const replace = await askSecret('New key (blank = keep existing)');
    if (replace) collected['GOOGLE_AI_API_KEY'] = replace;
  } else {
    const key = await askSecret('Google AI API key (blank = skip)');
    if (key) {
      collected['GOOGLE_AI_API_KEY'] = key;
      ok('Google key set.');
    } else {
      warn('Skipped. You can add it later via Dashboard → Credentials or .env');
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  step(4, TOTAL_STEPS, 'Gateway Config');
  print('  Configure the gateway address and sandbox mode.\n');

  let port = 18789;
  let bind = '127.0.0.1';
  let sandboxMode = 'all';

  if (!configExists) {
    const portStr = await ask('Gateway port', '18789');
    port = parseInt(portStr, 10) || 18789;

    const exposeNet = await confirm('Expose to local network? (bind 0.0.0.0 instead of 127.0.0.1)', false);
    if (exposeNet) {
      bind = '0.0.0.0';
      warn('Network-exposed gateway — ensure firewall rules are in place.');
    }

    print();
    print('  Sandbox mode controls which tool calls are isolated:');
    print(`    ${bold('all')}      — sandbox every tool call   ${dim('(safest, recommended)')}`);
    print(`    ${bold('none')}     — no sandbox                ${dim('(fastest, less safe)')}`);
    print(`    ${bold('untrusted')}— sandbox untrusted tools only`);
    print();
    sandboxMode = await ask('Sandbox mode', 'all');
    if (!['all', 'none', 'untrusted'].includes(sandboxMode)) sandboxMode = 'all';
    ok(`Sandbox: ${sandboxMode}`);
  } else {
    info('ai-desk.json already exists — skipping config generation.');
  }

  // ─────────────────────────────────────────────────────────────────────────
  step(5, TOTAL_STEPS, 'Writing Files');
  print();

  // Write .env
  const envContent = buildEnvFile(collected);
  writeFileSync(resolve('.env'), envContent, 'utf-8');
  ok('.env written');

  // Write ai-desk.json (only if it doesn't exist)
  if (!configExists) {
    const configContent = minimalConfig(port, bind, sandboxMode);
    writeFileSync(resolve('ai-desk.json'), configContent, 'utf-8');
    ok('ai-desk.json written');
  } else {
    info('ai-desk.json unchanged (already exists)');
  }

  // ─────────────────────────────────────────────────────────────────────────
  step(6, TOTAL_STEPS, 'Initial Auth Token');
  print('  Creating the auth token you will use to connect to the gateway.\n');

  // Lazy import to avoid loading gateway until .env is ready
  process.env['AI_DESK_MASTER_KEY'] = collected['AI_DESK_MASTER_KEY'];

  let tokenLine = '';
  try {
    const { AuthManager } = await import('../auth/auth-manager.js');
    const { loadConfig }  = await import('../config/config-loader.js');

    const { config } = loadConfig('ai-desk.json');
    const dataDir = process.env.AI_DESK_DATA_DIR ?? './.ai-desk-data';
    const auth = new AuthManager(config.gateway.auth, dataDir, collected['AI_DESK_MASTER_KEY']);
    const { token: rawToken } = auth.generateToken('onboard');
    auth.destroy();

    tokenLine = rawToken;
    ok(`Token created: ${bold(cyan(rawToken))}`);
    warn('This token is shown once — save it now.');
  } catch (e) {
    warn(`Could not generate token: ${(e as Error).message}`);
    info('Run  ai-desk token create  after starting the gateway.');
  }

  // ─────────────────────────────────────────────────────────────────────────
  step(7, TOTAL_STEPS, 'Security Check');
  print();

  try {
    const { loadConfig }  = await import('../config/config-loader.js');
    const { AuditEngine } = await import('../security/audit-engine.js');

    const { config } = loadConfig('ai-desk.json');
    const dataDir = process.env.AI_DESK_DATA_DIR ?? './.ai-desk-data';
    const engine = new AuditEngine(config, dataDir);
    const { score, passed, warned: warnCount, failed } = await engine.runFullAudit();

    const scoreColor = score >= 90 ? green : score >= 70 ? yellow : red;
    print(`  Score: ${bold(scoreColor(score + '%'))}  ` +
      `${green('✔ ' + passed)} passed  ${yellow('⚠ ' + warnCount)} warnings  ${red('✖ ' + failed)} failed`);

    if (failed > 0) {
      warn(`Run  ${bold('ai-desk security audit')}  to see what needs fixing.`);
    } else if (warnCount > 0) {
      info(`Run  ${bold('ai-desk security audit')}  to review warnings.`);
    } else {
      ok('All security checks passed.');
    }
  } catch (e) {
    warn(`Security audit skipped: ${(e as Error).message}`);
  }

  // ─────────────────────────────────────────────────────────────────────────
  step(8, TOTAL_STEPS, 'Install as System Daemon');
  print('  Run the gateway automatically on every system start / login.\n');

  const platformLabel: Record<string, string> = {
    win32:  'Windows Task Scheduler (runs at login)',
    linux:  'systemd service       (runs at boot, needs sudo)',
    darwin: 'macOS launchd agent   (runs at login)',
  };
  info(`Platform: ${platformLabel[process.platform] ?? process.platform}`);
  print();

  // --install-daemon flag skips the question and installs directly
  const wantDaemon = opts.installDaemon ?? await confirm('Install daemon now?', false);

  if (wantDaemon) {
    try {
      const { installDaemon } = await import('./daemon.js');
      process.stdout.write('  Installing…  ');
      await installDaemon('ai-desk.json');
      daemonInstalled = true;
      ok('Daemon installed and started.');
      info('It will restart automatically if it crashes, and start on next login/boot.');
    } catch (e) {
      const msg = (e as Error).message;
      err(`Daemon install failed: ${msg}`);
      if (process.platform === 'linux') {
        warn('Try:  sudo ai-desk daemon install');
      } else {
        warn('Try running this command from an Administrator terminal.');
      }
      info('You can install the daemon later with:  ai-desk daemon install');
    }
  } else {
    info(`Skipped. Run  ${bold('ai-desk daemon install')}  anytime to set it up.`);
  }

  // ── Start gateway now? ────────────────────────────────────────────────────
  let gatewayStarted = false;
  if (!daemonInstalled) {
    print();
    const startNow = await confirm('Start the gateway now in the background?', true);
    if (startNow) {
      try {
        const scriptPath = resolve(__dirname, 'index.js');
        const child = spawn(process.execPath, [scriptPath, 'gateway', '--config', 'ai-desk.json'], {
          detached: true,
          stdio: 'ignore',
          windowsHide: true,
          cwd: process.cwd(),
        });
        child.unref();
        gatewayStarted = true;
        // Give it a moment to bind the port
        await new Promise(r => setTimeout(r, 1200));
        ok(`Gateway started (PID ${child.pid})`);
        info(`Dashboard: ${cyan(`http://127.0.0.1:${port}/dashboard`)}`);
      } catch (e) {
        warn(`Could not start gateway: ${(e as Error).message}`);
        info(`Start manually with:  ${bold('npm start')}  or  ${bold('ai-desk gateway')}`);
      }
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  print();
  print(DIVIDER);
  print();
  print(`  ${bold(green('Setup complete!'))}  Here\'s how to get started:\n`);

  const hasAnthropicKey = !!(collected['ANTHROPIC_API_KEY']);
  const hasGoogleKey    = !!(collected['GOOGLE_AI_API_KEY']);

  if (!hasAnthropicKey && !hasGoogleKey) {
    warn('No API keys configured — add them via Dashboard → Credentials before chatting.');
  }

  if (daemonInstalled) {
    print(`  ${bold('1. Gateway')}  ${green('running as daemon')} — starts automatically on every login/boot`);
  } else if (gatewayStarted) {
    print(`  ${bold('1. Gateway')}  ${green('running in background')} — to stop: find PID with  ai-desk daemon status`);
  } else {
    print(`  ${bold('1. Start the gateway')}`);
    print(`     ${cyan('ai-desk gateway')}  ${dim('(or npm start)')}`);
  }
  print();
  print(`  ${bold('2. Open the dashboard')}`);
  print(`     ${cyan(`http://127.0.0.1:${port}/dashboard`)}`);
  print();
  print(`  ${bold('3. Connect a client')}`);
  if (tokenLine) {
    print(`     Token: ${cyan(tokenLine)}`);
  }
  print(`     Endpoint: ${cyan(`ws://127.0.0.1:${port}`)}`);
  print();
  print(`  ${bold('4. Other useful commands')}`);
  print(`     ${dim('ai-desk security audit')}   — run full security audit`);
  print(`     ${dim('ai-desk token create')}      — create more auth tokens`);
  print(`     ${dim('ai-desk skill list')}        — browse available skills`);
  print(`     ${dim('ai-desk models')}            — check model provider status`);
  print(`     ${dim('ai-desk onboard')}           — re-run this wizard anytime`);
  print(`     ${dim('ai-desk daemon install')}    — install as auto-start daemon`);
  print(`     ${dim('ai-desk daemon status')}     — check daemon status`);
  print();
  print(DIVIDER);
  print();
}
