/**
 * AI_DESK — First-Run Setup Server
 *
 * Starts a minimal HTTP server when no ai-desk.json / .env exists.
 * Serves the setup wizard SPA and handles the launch API.
 *
 * After the user completes setup in the browser:
 *   POST /setup/api/launch  → writes .env + ai-desk.json + creates auth token
 *                           → closes this server
 *                           → calls onLaunch(configPath) to start GatewayServer
 */
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { randomBytes } from 'node:crypto';
import { readClaudeCodeCredentials } from '../auth/credential-store.js';
import { getSetupHtml } from './setup-html.js';

export type LaunchCallback = (configPath: string) => Promise<void>;

export class SetupServer {
  private httpServer: ReturnType<typeof createServer>;
  private onLaunch: LaunchCallback;

  constructor(onLaunch: LaunchCallback) {
    this.onLaunch = onLaunch;
    this.httpServer = createServer((req, res) => { void this.handle(req, res); });
  }

  async start(port = 18789): Promise<void> {
    return new Promise((resolve, reject) => {
      this.httpServer.once('error', reject);
      this.httpServer.listen(port, '127.0.0.1', () => resolve());
    });
  }

  // ─── router ────────────────────────────────────────────────────────────────

  private async handle(req: IncomingMessage, res: ServerResponse): Promise<void> {
    const url    = (req.url ?? '/').split('?')[0];
    const method = (req.method ?? 'GET').toUpperCase();

    // Setup wizard SPA
    if ((url === '/' || url === '/setup' || url === '/setup/') && method === 'GET') {
      res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
      res.end(getSetupHtml());
      return;
    }

    // Pre-check: what is already configured?
    if (url === '/setup/api/check' && method === 'GET') {
      const cc = readClaudeCodeCredentials();
      this.json(res, {
        envExists:          existsSync(resolve('.env')),
        configExists:       existsSync(resolve('ai-desk.json')),
        masterKeySet:       !!process.env.AI_DESK_MASTER_KEY,
        anthropicSet:       !!process.env.ANTHROPIC_API_KEY,
        googleSet:          !!(process.env.GOOGLE_AI_API_KEY || process.env.GEMINI_API_KEY),
        openrouterSet:      !!process.env.OPENROUTER_API_KEY,
        claudeCodeAvailable: cc !== null,
        claudeCodeExpiresAt: cc?.expiresAt ?? null,
      });
      return;
    }

    // Generate a secure random master key (convenience endpoint)
    if (url === '/setup/api/generate-key' && method === 'GET') {
      this.json(res, { key: randomBytes(32).toString('hex') });
      return;
    }

    // Final launch: write files, start gateway
    if (url === '/setup/api/launch' && method === 'POST') {
      await this.withBody(req, async body => {
        await this.handleLaunch(res, body as SetupPayload);
      });
      return;
    }

    res.writeHead(404, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Not found' }));
  }

  // ─── launch handler ────────────────────────────────────────────────────────

  private async handleLaunch(res: ServerResponse, body: SetupPayload): Promise<void> {
    try {
      // Validate required fields
      if (!body.masterKey || body.masterKey.length < 16) {
        this.json(res, { error: 'masterKey must be at least 16 characters' }, 400);
        return;
      }
      const hasAnyKey = body.anthropicKey || body.googleKey || body.openrouterKey
        || readClaudeCodeCredentials() !== null;
      if (!hasAnyKey) {
        this.json(res, {
          error: 'At least one credential is required (Anthropic API key, Google API key, ' +
                 'OpenRouter API key, or Claude Code login)',
        }, 400);
        return;
      }

      const port = Number(body.port) || 18789;
      const bind = body.bind === '0.0.0.0' ? '0.0.0.0' : '127.0.0.1';

      // Write .env
      const envLines = [
        '# AI_DESK — generated by setup wizard',
        `AI_DESK_MASTER_KEY=${body.masterKey}`,
        `ANTHROPIC_API_KEY=${body.anthropicKey ?? ''}`,
        `GOOGLE_AI_API_KEY=${body.googleKey ?? ''}`,
        `OPENROUTER_API_KEY=${body.openrouterKey ?? ''}`,
      ];
      writeFileSync(resolve('.env'), envLines.join('\n') + '\n', 'utf-8');

      // Write ai-desk.json — auto-select best primary model based on what was provided
      const primaryModel = body.anthropicKey
        ? 'anthropic/claude-sonnet-4-6'
        : body.openrouterKey
          ? 'openrouter/anthropic/claude-sonnet-4-5'
          : body.googleKey
            ? 'google/gemini-2.5-flash'
            : 'anthropic/claude-sonnet-4-6'; // claude code fallback

      const config = buildConfig(port, bind, body.sandbox ?? 'all', primaryModel);
      writeFileSync(resolve('ai-desk.json'), JSON.stringify(config, null, 2), 'utf-8');

      // Inject env vars into current process so GatewayServer can read them
      process.env['AI_DESK_MASTER_KEY']  = body.masterKey;
      process.env['ANTHROPIC_API_KEY']   = body.anthropicKey  ?? '';
      process.env['GOOGLE_AI_API_KEY']   = body.googleKey     ?? '';
      process.env['OPENROUTER_API_KEY']  = body.openrouterKey ?? '';

      // Generate the initial auth token BEFORE launching (we need it for the response)
      const { AuthManager } = await import('../auth/auth-manager.js');
      const dataDir = process.env.AI_DESK_DATA_DIR ?? './.ai-desk-data';
      const tempAuth = new AuthManager(config.gateway.auth, dataDir, body.masterKey);
      const { token } = tempAuth.generateToken('setup-wizard');
      tempAuth.destroy();

      // Respond immediately so the browser gets the token before we close the server
      this.json(res, {
        ok:           true,
        token,
        dashboardUrl: `http://${bind === '0.0.0.0' ? '127.0.0.1' : bind}:${port}/dashboard`,
        chatUrl:      `http://${bind === '0.0.0.0' ? '127.0.0.1' : bind}:${port}/dashboard#chat`,
      });

      // Close setup server, then start the real gateway
      await new Promise<void>(r => this.httpServer.close(() => r()));
      await new Promise(r => setTimeout(r, 200)); // tiny gap for OS to free the port

      await this.onLaunch('ai-desk.json');
    } catch (err) {
      this.json(res, { error: (err as Error).message }, 500);
    }
  }

  // ─── helpers ───────────────────────────────────────────────────────────────

  private withBody(req: IncomingMessage, handler: (body: unknown) => Promise<void>): Promise<void> {
    return new Promise((resolve, reject) => {
      const chunks: Buffer[] = [];
      req.on('data', (c: Buffer) => chunks.push(c));
      req.on('end', async () => {
        try {
          const body = JSON.parse(Buffer.concat(chunks).toString('utf-8'));
          await handler(body);
          resolve();
        } catch (e) { reject(e); }
      });
      req.on('error', reject);
    });
  }

  private json(res: ServerResponse, data: unknown, status = 200): void {
    res.writeHead(status, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(data));
  }
}

// ─── helpers ──────────────────────────────────────────────────────────────────

interface SetupPayload {
  masterKey:      string;
  anthropicKey?:  string;
  googleKey?:     string;
  openrouterKey?: string;
  port?:          number;
  bind?:          string;
  sandbox?:       string;
}

function buildConfig(port: number, bind: string, sandbox: string, primaryModel: string) {
  // Build failover list from what was supplied (no duplicates, no primary)
  const failover = [
    primaryModel !== 'google/gemini-2.5-flash' ? 'google/gemini-2.5-flash' : '',
    primaryModel !== 'anthropic/claude-sonnet-4-6' ? 'anthropic/claude-sonnet-4-6' : '',
  ].filter(Boolean);

  return {
    gateway: {
      bind, port,
      auth: { mode: 'token' as const, maxFailedAttempts: 5, lockoutDurationMs: 300000, tokenExpiryMs: 86400000 },
      rateLimit: { maxPerSecond: 10, maxConnections: 50 },
      maxFrameSize: 1048576, heartbeatIntervalMs: 30000,
    },
    agents: {
      defaults: {
        model: {
          primary: primaryModel,
          failover,
          compaction: 'anthropic/claude-haiku-4-5-20251001',
        },
        timeoutSeconds: 172800,
        sandbox: { mode: sandbox, timeoutMs: 30000, maxMemoryMb: 512, networkAccess: false },
        tools: { profile: 'deny-all' },
        budget: {
          daily: { tokens: 500000, cost: 5.0 }, monthly: { tokens: 10000000, cost: 50.0 },
          perRun: { maxTokens: 50000 }, warningThreshold: 0.8, action: 'warn',
        },
        subagents: {
          model: 'google/gemini-2.5-flash', maxDepth: 3, maxConcurrent: 5,
          sandbox: 'require', runTimeoutSeconds: 300, budget: 'inherit',
        },
      },
      list: [{ id: 'main', default: true, workspace: '.', tools: { profile: 'readonly' } }],
    },
    cache:  { enabled: true, backend: 'sqlite', ttlSeconds: 3600 },
    memory: { backend: 'none', compaction: { threshold: 0.6, model: 'anthropic/claude-haiku-4-5-20251001' } },
    mcp:    { security: { sandboxAll: true, denyCapabilities: [], perServerBudget: { dailyTokens: 50000 } }, servers: {} },
    notifications: { budgetAlerts: true, subagentCompletion: true, securityAlerts: true },
  };
}
