/**
 * AI_DESK — Project Exporter
 *
 * Exports project state to <workspace>/.aidesk/project.md for human readability.
 * Best-effort: never throws (errors are logged as warnings).
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { Project, ProjectArtifact, TeamRun, TeamRunTask } from './project-store.js';

export interface ExportInput {
  project: Project;
  artifacts: ProjectArtifact[];
  recentRuns: TeamRun[];
  latestRunTasks?: TeamRunTask[];
}

export async function exportProjectMarkdown(input: ExportInput): Promise<void> {
  try {
    const { project, artifacts, recentRuns, latestRunTasks } = input;
    const aidesk = join(project.workspacePath, '.aidesk');
    await mkdir(aidesk, { recursive: true });

    const lines: string[] = [];
    lines.push(`# ${project.name}`);
    lines.push('');
    lines.push(`> Generated by AI-Desk · Project ID: \`${project.id}\``);
    lines.push('');

    if (project.brief) {
      lines.push('## Brief');
      lines.push(project.brief);
      lines.push('');
    }

    lines.push('## Artifacts');
    if (artifacts.length === 0) {
      lines.push('_No artifacts yet._');
    } else {
      for (const a of artifacts) {
        const summary = a.summary ? ` — ${a.summary}` : '';
        lines.push(`- \`${a.path}\`${summary}`);
      }
    }
    lines.push('');

    lines.push('## Recent Runs');
    if (recentRuns.length === 0) {
      lines.push('_No runs yet._');
    } else {
      for (const run of recentRuns) {
        const icon = run.status === 'done' ? '✅' : run.status === 'failed' ? '❌' : '⏳';
        const date = new Date(run.startedAt).toISOString().slice(0, 16).replace('T', ' ');
        lines.push(`- ${icon} **${run.kind}** · ${run.goal} · \`${date}\``);
      }
    }
    lines.push('');

    if (latestRunTasks && latestRunTasks.length > 0) {
      lines.push('## Latest Run Tasks');
      for (const t of latestRunTasks) {
        const icon = t.status === 'done' ? '✅' : t.status === 'failed' ? '❌' : t.status === 'skipped' ? '⏭️' : '⏳';
        lines.push(`- ${icon} **${t.label}** (\`${t.agentId}\`)`);
      }
      lines.push('');
    }

    lines.push(`_Last updated: ${new Date().toISOString()}_`);

    await writeFile(join(aidesk, 'project.md'), lines.join('\n'), 'utf-8');
  } catch (err) {
    // Best-effort — log but don't fail the run
    console.warn('[project-exporter] Failed to export project.md:', (err as Error).message);
  }
}
