/**
 * AI_DESK — Project Store
 *
 * Persists Team Projects, Artifacts, Runs, and Run Tasks in SQLite.
 * Source of truth for resumable team runs and project state.
 */
import Database from 'better-sqlite3';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';
import { mkdirSync } from 'node:fs';

// ── Types ──────────────────────────────────────────────────────────────────

export interface Project {
  id: string;                      // 'proj-' + 8 hex
  teamId: string;
  name: string;                    // generated from initial goal, editable
  workspacePath: string;           // absolute path
  brief: string;                   // markdown, generated by lead agent on init
  status: 'active' | 'archived';
  createdAt: number;
  updatedAt: number;
  lastRunId: string | null;
}

export interface ProjectArtifact {
  projectId: string;
  path: string;                    // relative to workspacePath
  kind: 'file' | 'dir';
  summary: string;                 // 1-line description
  createdInRunId: string;
  lastModifiedInRunId: string;
  lastModifiedAt: number;
  bytes: number;
}

export interface TeamRun {
  id: string;                      // 'run-' + 8 hex
  projectId: string | null;        // null = ad-hoc run
  teamId: string;
  goal: string;
  kind: 'init' | 'feature' | 'bugfix' | 'refactor' | 'question';
  status: 'running' | 'done' | 'failed' | 'paused';
  channelId: string;
  peerId: string;
  startedAt: number;
  finishedAt: number | null;
  synthesis: string | null;
}

export interface TeamRunTask {
  runId: string;
  taskId: string;                  // matches TaskDefinition.id
  label: string;
  agentId: string;
  prompt: string;
  dependsJson: string;             // JSON array of task id strings
  status: 'pending' | 'running' | 'done' | 'failed' | 'skipped';
  result: string | null;
  error: string | null;
  startedAt: number | null;
  finishedAt: number | null;
}

// ── Store ──────────────────────────────────────────────────────────────────

export class ProjectStore {
  private db: ReturnType<typeof Database>;

  constructor(dataDir: string) {
    mkdirSync(dataDir, { recursive: true });
    this.db = Database(join(dataDir, 'projects.db'));
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS projects (
        id              TEXT    PRIMARY KEY,
        team_id         TEXT    NOT NULL,
        name            TEXT    NOT NULL,
        workspace_path  TEXT    NOT NULL,
        brief           TEXT    NOT NULL DEFAULT '',
        status          TEXT    NOT NULL DEFAULT 'active',
        created_at      INTEGER NOT NULL,
        updated_at      INTEGER NOT NULL,
        last_run_id     TEXT
      );

      CREATE INDEX IF NOT EXISTS idx_projects_team_id ON projects (team_id);

      CREATE TABLE IF NOT EXISTS project_artifacts (
        project_id              TEXT    NOT NULL,
        path                    TEXT    NOT NULL,
        kind                    TEXT    NOT NULL DEFAULT 'file',
        summary                 TEXT    NOT NULL DEFAULT '',
        created_in_run_id       TEXT    NOT NULL,
        last_modified_in_run_id TEXT    NOT NULL,
        last_modified_at        INTEGER NOT NULL,
        bytes                   INTEGER NOT NULL DEFAULT 0,
        PRIMARY KEY (project_id, path)
      );

      CREATE TABLE IF NOT EXISTS team_runs (
        id          TEXT    PRIMARY KEY,
        project_id  TEXT,
        team_id     TEXT    NOT NULL,
        goal        TEXT    NOT NULL,
        kind        TEXT    NOT NULL DEFAULT 'feature',
        status      TEXT    NOT NULL DEFAULT 'running',
        channel_id  TEXT    NOT NULL,
        peer_id     TEXT    NOT NULL,
        started_at  INTEGER NOT NULL,
        finished_at INTEGER,
        synthesis   TEXT
      );

      CREATE INDEX IF NOT EXISTS idx_team_runs_project_id ON team_runs (project_id);
      CREATE INDEX IF NOT EXISTS idx_team_runs_team_id    ON team_runs (team_id);

      CREATE TABLE IF NOT EXISTS team_run_tasks (
        run_id       TEXT    NOT NULL,
        task_id      TEXT    NOT NULL,
        label        TEXT    NOT NULL,
        agent_id     TEXT    NOT NULL,
        prompt       TEXT    NOT NULL,
        depends_json TEXT    NOT NULL DEFAULT '[]',
        status       TEXT    NOT NULL DEFAULT 'pending',
        result       TEXT,
        error        TEXT,
        started_at   INTEGER,
        finished_at  INTEGER,
        PRIMARY KEY (run_id, task_id)
      );
    `);
  }

  // ── Project ──────────────────────────────────────────────────────────────

  createProject(input: {
    teamId: string;
    name: string;
    workspacePath: string;
    brief?: string;
  }): Project {
    const id  = 'proj-' + randomBytes(4).toString('hex');
    const now = Date.now();
    this.db.prepare(`
      INSERT INTO projects (id, team_id, name, workspace_path, brief, status, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, 'active', ?, ?)
    `).run(id, input.teamId, input.name, input.workspacePath, input.brief ?? '', now, now);
    return this.getProject(id)!;
  }

  getProject(id: string): Project | undefined {
    const row = this.db.prepare('SELECT * FROM projects WHERE id = ?').get(id) as Record<string, unknown> | undefined;
    return row ? this.toProject(row) : undefined;
  }

  findActiveByTeam(teamId: string): Project | undefined {
    const row = this.db.prepare(`
      SELECT * FROM projects WHERE team_id = ? AND status = 'active'
      ORDER BY updated_at DESC LIMIT 1
    `).get(teamId) as Record<string, unknown> | undefined;
    return row ? this.toProject(row) : undefined;
  }

  listByTeam(teamId: string): Project[] {
    return (this.db.prepare(
      'SELECT * FROM projects WHERE team_id = ? ORDER BY updated_at DESC',
    ).all(teamId) as Record<string, unknown>[]).map(r => this.toProject(r));
  }

  listAll(limit = 50): Project[] {
    return (this.db.prepare(
      'SELECT * FROM projects ORDER BY updated_at DESC LIMIT ?',
    ).all(limit) as Record<string, unknown>[]).map(r => this.toProject(r));
  }

  updateBrief(id: string, brief: string): void {
    this.db.prepare('UPDATE projects SET brief = ?, updated_at = ? WHERE id = ?')
      .run(brief, Date.now(), id);
  }

  updateProjectName(id: string, name: string): void {
    this.db.prepare('UPDATE projects SET name = ?, updated_at = ? WHERE id = ?')
      .run(name, Date.now(), id);
  }

  setLastRunId(id: string, runId: string): void {
    this.db.prepare('UPDATE projects SET last_run_id = ?, updated_at = ? WHERE id = ?')
      .run(runId, Date.now(), id);
  }

  archive(id: string): void {
    this.db.prepare("UPDATE projects SET status = 'archived', updated_at = ? WHERE id = ?")
      .run(Date.now(), id);
  }

  /** Bump updated_at → now so findActiveByTeam returns this project (used by @project switch) */
  touchProject(id: string): void {
    this.db.prepare('UPDATE projects SET updated_at = ? WHERE id = ?').run(Date.now(), id);
  }

  // ── Artifact ──────────────────────────────────────────────────────────────

  upsertArtifact(input: {
    projectId: string;
    path: string;
    kind?: 'file' | 'dir';
    summary?: string;
    runId: string;
    bytes?: number;
  }): void {
    const now = Date.now();
    this.db.prepare(`
      INSERT INTO project_artifacts
        (project_id, path, kind, summary, created_in_run_id, last_modified_in_run_id, last_modified_at, bytes)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?)
      ON CONFLICT (project_id, path) DO UPDATE SET
        kind                    = excluded.kind,
        summary                 = CASE WHEN excluded.summary != '' THEN excluded.summary ELSE summary END,
        last_modified_in_run_id = excluded.last_modified_in_run_id,
        last_modified_at        = excluded.last_modified_at,
        bytes                   = excluded.bytes
    `).run(
      input.projectId,
      input.path,
      input.kind ?? 'file',
      input.summary ?? '',
      input.runId,
      input.runId,
      now,
      input.bytes ?? 0,
    );
  }

  listArtifacts(projectId: string): ProjectArtifact[] {
    return (this.db.prepare(
      'SELECT * FROM project_artifacts WHERE project_id = ? ORDER BY path',
    ).all(projectId) as Record<string, unknown>[]).map(r => this.toArtifact(r));
  }

  getArtifact(projectId: string, path: string): ProjectArtifact | undefined {
    const row = this.db.prepare(
      'SELECT * FROM project_artifacts WHERE project_id = ? AND path = ?',
    ).get(projectId, path) as Record<string, unknown> | undefined;
    return row ? this.toArtifact(row) : undefined;
  }

  updateArtifactSummary(projectId: string, path: string, summary: string): void {
    this.db.prepare(
      'UPDATE project_artifacts SET summary = ? WHERE project_id = ? AND path = ?',
    ).run(summary, projectId, path);
  }

  listArtifactsWithoutSummary(projectId: string): ProjectArtifact[] {
    return (this.db.prepare(
      "SELECT * FROM project_artifacts WHERE project_id = ? AND (summary IS NULL OR summary = '') ORDER BY path",
    ).all(projectId) as Record<string, unknown>[]).map(r => this.toArtifact(r));
  }

  // ── Run ──────────────────────────────────────────────────────────────────

  createRun(input: {
    projectId: string | null;
    teamId: string;
    goal: string;
    kind: TeamRun['kind'];
    channelId: string;
    peerId: string;
  }): TeamRun {
    const id  = 'run-' + randomBytes(4).toString('hex');
    const now = Date.now();
    this.db.prepare(`
      INSERT INTO team_runs (id, project_id, team_id, goal, kind, status, channel_id, peer_id, started_at)
      VALUES (?, ?, ?, ?, ?, 'running', ?, ?, ?)
    `).run(id, input.projectId ?? null, input.teamId, input.goal, input.kind, input.channelId, input.peerId, now);
    return this.getRun(id)!;
  }

  getRun(id: string): TeamRun | undefined {
    const row = this.db.prepare('SELECT * FROM team_runs WHERE id = ?').get(id) as Record<string, unknown> | undefined;
    return row ? this.toRun(row) : undefined;
  }

  updateRunStatus(id: string, status: TeamRun['status'], synthesis?: string): void {
    this.db.prepare(`
      UPDATE team_runs SET status = ?, finished_at = ?, synthesis = COALESCE(?, synthesis) WHERE id = ?
    `).run(status, status === 'running' ? null : Date.now(), synthesis ?? null, id);
  }

  listRunsByProject(projectId: string, limit = 20): TeamRun[] {
    return (this.db.prepare(
      'SELECT * FROM team_runs WHERE project_id = ? ORDER BY started_at DESC LIMIT ?',
    ).all(projectId, limit) as Record<string, unknown>[]).map(r => this.toRun(r));
  }

  listRecentRunsByTeam(teamId: string, limit = 5): TeamRun[] {
    return (this.db.prepare(
      'SELECT * FROM team_runs WHERE team_id = ? ORDER BY started_at DESC LIMIT ?',
    ).all(teamId, limit) as Record<string, unknown>[]).map(r => this.toRun(r));
  }

  // ── Run Task ──────────────────────────────────────────────────────────────

  bulkInsertTasks(runId: string, tasks: Array<{
    taskId: string;
    label: string;
    agentId: string;
    prompt: string;
    depends: string[];
  }>): void {
    const insert = this.db.prepare(`
      INSERT OR IGNORE INTO team_run_tasks (run_id, task_id, label, agent_id, prompt, depends_json, status)
      VALUES (?, ?, ?, ?, ?, ?, 'pending')
    `);
    const insertMany = this.db.transaction((rows: typeof tasks) => {
      for (const t of rows) {
        insert.run(runId, t.taskId, t.label, t.agentId, t.prompt, JSON.stringify(t.depends));
      }
    });
    insertMany(tasks);
  }

  updateTask(runId: string, taskId: string, patch: {
    status?: TeamRunTask['status'];
    result?: string;
    error?: string;
    startedAt?: number;
    finishedAt?: number;
  }): void {
    const fields: string[] = [];
    const values: unknown[] = [];
    if (patch.status     !== undefined) { fields.push('status = ?');      values.push(patch.status); }
    if (patch.result     !== undefined) { fields.push('result = ?');      values.push(patch.result); }
    if (patch.error      !== undefined) { fields.push('error = ?');       values.push(patch.error); }
    if (patch.startedAt  !== undefined) { fields.push('started_at = ?');  values.push(patch.startedAt); }
    if (patch.finishedAt !== undefined) { fields.push('finished_at = ?'); values.push(patch.finishedAt); }
    if (!fields.length) return;
    values.push(runId, taskId);
    this.db.prepare(`UPDATE team_run_tasks SET ${fields.join(', ')} WHERE run_id = ? AND task_id = ?`).run(...values);
  }

  listTasksByRun(runId: string): TeamRunTask[] {
    return (this.db.prepare(
      'SELECT * FROM team_run_tasks WHERE run_id = ? ORDER BY rowid',
    ).all(runId) as Record<string, unknown>[]).map(r => this.toTask(r));
  }

  close(): void { this.db.close(); }

  // ── Row mappers ───────────────────────────────────────────────────────────

  private toProject(r: Record<string, unknown>): Project {
    return {
      id:            r['id']             as string,
      teamId:        r['team_id']        as string,
      name:          r['name']           as string,
      workspacePath: r['workspace_path'] as string,
      brief:         r['brief']          as string,
      status:        r['status']         as 'active' | 'archived',
      createdAt:     r['created_at']     as number,
      updatedAt:     r['updated_at']     as number,
      lastRunId:     (r['last_run_id']   as string | null) ?? null,
    };
  }

  private toArtifact(r: Record<string, unknown>): ProjectArtifact {
    return {
      projectId:            r['project_id']               as string,
      path:                 r['path']                     as string,
      kind:                 r['kind']                     as 'file' | 'dir',
      summary:              r['summary']                  as string,
      createdInRunId:       r['created_in_run_id']        as string,
      lastModifiedInRunId:  r['last_modified_in_run_id']  as string,
      lastModifiedAt:       r['last_modified_at']         as number,
      bytes:                r['bytes']                    as number,
    };
  }

  private toRun(r: Record<string, unknown>): TeamRun {
    return {
      id:          r['id']          as string,
      projectId:   (r['project_id']  as string | null) ?? null,
      teamId:      r['team_id']     as string,
      goal:        r['goal']        as string,
      kind:        r['kind']        as TeamRun['kind'],
      status:      r['status']      as TeamRun['status'],
      channelId:   r['channel_id']  as string,
      peerId:      r['peer_id']     as string,
      startedAt:   r['started_at']  as number,
      finishedAt:  (r['finished_at'] as number | null) ?? null,
      synthesis:   (r['synthesis']   as string | null) ?? null,
    };
  }

  private toTask(r: Record<string, unknown>): TeamRunTask {
    return {
      runId:       r['run_id']       as string,
      taskId:      r['task_id']      as string,
      label:       r['label']        as string,
      agentId:     r['agent_id']     as string,
      prompt:      r['prompt']       as string,
      dependsJson: r['depends_json'] as string,
      status:      r['status']       as TeamRunTask['status'],
      result:      (r['result']      as string | null) ?? null,
      error:       (r['error']       as string | null) ?? null,
      startedAt:   (r['started_at']  as number | null) ?? null,
      finishedAt:  (r['finished_at'] as number | null) ?? null,
    };
  }
}
